name: Nabil CI/CD

on: 
    workflow_dispatch:
      inputs:
        build-and-push:
          type: boolean
          description: Wether i choose to build and push or not
          default: true
  

jobs:
  checkout-and-test:
    name: checkouting and testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        id: setup-node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install Dependencies
        id: npm-ci
        run: npm ci

      - name: Run Lint
        id: npm-lint
        run: npm run lint

      - name: Run Test
        id: npm-ci-test
        run: npm run test

  build-and-push:
    name: Build and push docker image
    runs-on: ubuntu-latest
    needs: checkout-and-test
    steps:
      - name: Failing build and push
        if: ${{ !inputs.build-and-push}}
        run: exit 1
      - name: Checkout
        id: checkout
        uses: actions/checkout@v4
      - name: Login to Dockerhub
        env:
            DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/github-action-school .
      - name: Push to Dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/github-action-school
